final_correct_version_push

diff --git a/.github/workflows/deploy-secure.yml b/.github/workflows/deploy-secure.yml
--- a/.github/workflows/deploy-secure.yml
+++ b/.github/workflows/deploy-secure.yml
@@ -356,20 +356,20 @@ jobs:
             sudo mkdir -p /home/ubuntu/secdebt-reports
             echo "Pulling latest image..."
 
-            if ! sudo docker pull sanudocker11/secure_vault_secure:latest; then
+            if ! sudo docker pull sanudocker11/secure_vault_secure:${{ github.sha }}; then
                 echo "Docker pull failed."
                 exit 1
             fi
             
             echo "Image pulled successfully."
             
-            sudo docker image inspect sanudocker11/secure_vault_secure:latest >/dev/null
+            sudo docker image inspect sanudocker11/secure_vault_secure:${{ github.sha }} >/dev/null
             echo "Current containers"
             sudo docker ps 
 
-            echo "Saving current running image..."
+            
 
-            CURRENT_IMAGE=""
+      
             
             if sudo docker ps -a --format '{{.Names}}' | grep -q '^securevault_secure_app$'; then
             
@@ -424,7 +424,7 @@ jobs:
               -e SECRET_KEY="${{ secrets.SECRET_KEY_SECURE }}" \
               -e VAULT_ENCRYPTION_KEY="${{ secrets.VAULT_ENCRYPTION_KEY_SECURE }}" \
               -e SECDEBT_INGEST_TOKEN="${{ secrets.SECDEBT_INGEST_TOKEN }}" \
-              sanudocker11/secure_vault_secure:latest
+              sanudocker11/secure_vault_secure:${{ github.sha }}
 
             sleep 20
 
@@ -445,33 +445,30 @@ jobs:
             
             if [ "${HEALTHY:-false}" != "true" ]; then
 
-                echo "Application failed health check."
+                echo "Deployment failed."
             
                 sudo docker logs securevault_secure_app || true
             
                 sudo docker stop securevault_secure_app || true
                 sudo docker rm securevault_secure_app || true
             
-                if [ -n "$CURRENT_IMAGE" ]; then
+                echo "Rolling back to stable image..."
             
-                    echo "Rolling back to previous image..."
+                sudo docker pull sanudocker11/secure_vault_secure:stable
             
-                    sudo docker run -d \
-                      --name securevault_secure_app \
-                      --network securevault-secure-net \
-                      -p 80:8000 \
-                      -v /home/ubuntu/secdebt-reports:/reports \
-                      -e DATABASE_URL="postgresql://securevault:securevault@securevault_secure_db:5432/securevault" \
-                      -e SECRET_KEY="${{ secrets.SECRET_KEY_SECURE }}" \
-                      -e VAULT_ENCRYPTION_KEY="${{ secrets.VAULT_ENCRYPTION_KEY_SECURE }}" \
-                      -e SECDEBT_INGEST_TOKEN="${{ secrets.SECDEBT_INGEST_TOKEN }}" \
-                      "$CURRENT_IMAGE"
-            
-                    echo "Rollback completed."
-            
-                fi
+                sudo docker run -d \
+                  --name securevault_secure_app \
+                  --network securevault-secure-net \
+                  -p 80:8000 \
+                  -v /home/ubuntu/secdebt-reports:/reports \
+                  -e DATABASE_URL="postgresql://securevault:securevault@securevault_secure_db:5432/securevault" \
+                  -e SECRET_KEY="${{ secrets.SECRET_KEY_SECURE }}" \
+                  -e VAULT_ENCRYPTION_KEY="${{ secrets.VAULT_ENCRYPTION_KEY_SECURE }}" \
+                  -e SECDEBT_INGEST_TOKEN="${{ secrets.SECDEBT_INGEST_TOKEN }}" \
+                  sanudocker11/secure_vault_secure:stable
             
                 exit 1
+            
             fi
             
             echo "Deployment successful."
